[package]
name = "java-typst"
version = "0.2.0"
edition = "2021"

[dependencies]
typst = "0.12.0"
typst-assets = {version = "0.12.0", features = ["fonts"]}
typst-pdf = "0.12.0"
#typst-as-library dependencies
comemo = "0.4"
# Fetching and unzipping packages
zune-inflate = { version = "0.2", default-features = false, features = [
    "gzip",
    "std",
] }
tar = "0.4"
ureq = "3.0.5"
# utils
time = "0.3"
ttf-parser = "0.25.1"

jni = "0.21.1"

[lib]
crate-type = ["cdylib"]